var hxLabels = {
    "@bypassvolume": "Bypass Volume",
    "@cab": "Cab",
    "@enabled": "Enabled",
    "@model": "Model",
    "@path": "Path",
    "@position": "Position",
    "@stereo": "Stereo",
    "@trails": "Trails",
    "@type": "Type",
    "125Hz": "125Hz",
    "16kHz": "16kHz",
    "1kHz": "1kHz",
    "2200Hz": "2200Hz",
    "240Hz": "240Hz",
    "250Hz": "250Hz",
    "2kHz": "2kHz",
    "31p25Hz": "31p25Hz",
    "4kHz": "4kHz",
    "500Hz": "500Hz",
    "62p5Hz": "62p5Hz",
    "6600Hz": "6600Hz",
    "750Hz": "750Hz",
    "80Hz": "80Hz",
    "8kHz": "8kHz",
    "AM": "AM",
    "AM/FM": "AM/FM",
    "AMFreq": "AM Frequency",
    "Amount": "Amount",
    "Asym": "Asym",
    "Attack": "Attack",
    "Auto": "Auto",
    "Balance": "Balance",
    "Bass": "Bass",
    "BassFreq": "Bass Frequency",
    "BBD Size": "BBD Size",
    "Bias": "Bias",
    "BiasX": "Bias X",
    "BitDepth": "Bit Depth",
    "Blend": "Blend",
    "Boost": "Boost",
    "Bright": "Bright",
    "C45": "C45",
    "Cents1": "Cents 1",
    "Cents2": "Cents 2",
    "ChorusIntensity": "Chorus Intensity",
    "CH Vib": "Chorus Vibration",
    "ChVol": "Channel Volume",
    "Clipping": "Clipping",
    "CloseThreshold": "Close Threshold",
    "Color": "Color",
    "Comp": "Compression",
    "Compress": "Compression",
    "Condition": "Condition",
    "CV Decay": "CV Decay",
    "CV Dynamics": "CV Dynamics",
    "CV Tracking": "CV Tracking",
    "Decay": "Decay",
    "Delay": "Delay",
    "DelayVoice1": "Delay Voice 1",
    "DelayVoice2": "Delay Voice 2",
    "Depth": "Depth",
    "Depth1": "Depth 1",
    "Depth2": "Depth 2",
    "Depth3": "Depth 3",
    "Detector": "Detector",
    "Diffusion": "Diffusion",
    "Direction": "Direction",
    "Distortion": "Distortion",
    "Doubles": "Doubles",
    "Drive": "Drive",
    "Dry Level": "Dry Level",
    "DryLevel": "Dry Level",
    "DryPan": "Dry Pan",
    "DryThru": "Dry Thru",
    "Ducking": "Ducking",
    "DutyCycle": "DutyCycle",
    "DutyVoice1": "Duty Voice 1",
    "DutyVoice2": "Duty Voice 2",
    "DutyVoice3": "Duty Voice 3",
    "DynAttack": "Dyn Attack",
    "DynRel": "Dyn Release",
    "DynType": "Dyn Type",
    "Emphasis": "Emphasis",
    "End": "End",
    "Enhance": "Enhance",
    "Env Input": "Envelope Input",
    "Env Lag": "Envelope Lag",
    "FM Voice3to1": "FM Voice 3 to 1",
    "FastSpeed": "Fast Speed",
    "Fat": "Fat",
    "FBTone": "Feedback Tone",
    "FcHigh": "Fc High",
    "FcLow": "Fc Low",
    "Feedback": "Feedback",
    "Filter": "Filter",
    "FilterGain": "FilterGain",
    "FilterMatrix": "Filter Matrix",
    "FilterQ": "FilterQ",
    "FilterType": "Filter Type",
    "FMAmount": "FM Amount",
    "FMDuty": "FM Duty",
    "FMOctave": "FM Octave",
    "FMPitch": "FM Pitch",
    "FMShape": "FM Shape",
    "Focus": "Focus",
    "Freq": "Freq",
    "FreqDepth": "Freq Depth",
    "Frequency": "Frequency",
    "Fuzz": "Fuzz",
    "FuzzGain": "Fuzz Gain",
    "FuzzLevel": "FuzzLevel",
    "FuzzOct": "Fuzz Oct",
    "FuzzTone": "Fuzz Tone",
    "FuzzType": "Fuzz Type",
    "Gain": "Gain",
    "Gate": "Gate",
    "Grit": "Grit",
    "Grunt": "Grunt",
    "Harmonic": "Harmonic",
    "HBE": "HBE",
    "Headroom": "Headroom",
    "Heads 1-2": "Heads 1-2",
    "Heads 3-4": "Heads 3-4",
    "Heel": "Heel",
    "Hi Gain": "High Gain",
    "Hi Thresh": "High Threshold",
    "Hi X Freq": "High Crossover Frequency",
    "HiMid": "High Mid",
    "HiMidFreq": "High Mid Freq",
    "HighCut": "High Cut",
    "highCut": "High Cut",
    "HighFreq": "High Frequency",
    "HighGain": "High Gain",
    "HighQ": "High Q",
    "HoldTime": "Hold Time",
    "Horn Depth": "Horn Depth",
    "Index": "Index",
    "Intensity": "Intensity",
    "Interval1": "Interval 1",
    "Interval2": "Interval 2",
    "IntervalVoice1": "Interval Voice 1",
    "IntervalVoice2": "Interval Voice 2",
    "Key": "Key",
    "KeyVoice1": "Key Voice 1",
    "KeyVoice2": "Key Voice 2",
    "Knee": "Knee",
    "LampBias": "Lamp Bias",
    "Left": "Left",
    "Left Time": "Left Time",
    "LeftBoost": "Left Boost",
    "LeftFeedback": "Left Feedback",
    "Level": "Level",
    "LevelRootVoice": "Level Root Voice",
    "LevelVoice1": "Level Voice 1",
    "LevelVoice2": "Level Voice 2",
    "LevelVoice3": "Level Voice 3",
    "LFeedback": "Left Feedback",
    "LFO": "LFO",
    "LFORate": "LFO Rate",
    "LFOShape": "LFO Shape",
    "Lo Gain": "Low Gain",
    "Lo Thresh": "Low Threshold",
    "Lo X Freq": "Low Crossover Frequency",
    "LoMid": "Lo Mid",
    "LoMidFreq": "Low Mid Frequncy",
    "LowCut": "Low Cut",
    "LowFreq": "Low Frequency",
    "LowGain": "Low Gain",
    "LowQ": "Low Q",
    "LPHP": "LPHP",
    "LR In Swap": "LR In Swap",
    "LTime": "Left Time",
    "Manual": "Manual",
    "Master": "Master",
    "Max Delay": "Max Delay",
    "Mid": "Mid",
    "Mid Gain": "Mid Gain",
    "Mid Thresh": "Mid Threshold",
    "MidFreq": "Mid Frequency",
    "MidGain": "Mid Gain",
    "MidQ": "Mid Q",
    "Mix": "Mix",
    "MixL": "Mix Left",
    "MixR": "Mix Right",
    "Mod Mix": "Mod Mix",
    "ModSpeed": "Mod Speed",
    "Mode": "Mode",
    "Modulation": "Modulation",
    "ModulationMode": "Modulation Mode",
    "Noise": "Noise",
    "Normal": "Normal",
    "Notch Freq": "Notch Freq",
    "Notch Gain": "Notch Gain",
    "ODGain": "OD Gain",
    "ODLevel": "OD Level",
    "ODLowBoost": "OD Low Boost",
    "ODTone": "OD Tone",
    "Octave": "Octave",
    "OctaveVoice1": "Octave Voice 1",
    "OctaveVoice2": "Octave Voice 2",
    "OctaveVoice3": "Octave Voice 3",
    "Offset": "Offset",
    "OpenThreshold": "Open Threshold",
    "Osc1Freq": "OSC Frequency 1",
    "Osc1Glide": "OSC Glide 1",
    "Osc1Level": "OSC Level 1",
    "Osc1Note": "OSC Note 1",
    "Osc1Octave": "OSC Octave 1",
    "Osc1Pan": "OSC Pan 1",
    "Osc1Shape": "OSC Shape 1",
    "Osc2Freq": "OSC Frequency 2",
    "Osc2Glide": "OSC Glide 2",
    "Osc2Level": "OSC Level 2",
    "Osc2Note": "OSC Note 2",
    "Osc2Octave": "OSC Octave 2",
    "Osc2Pan": "OSC Pan 2",
    "Osc2Shape": "OSC Shape 2",
    "Osc3Freq": "OSC Frequency 3",
    "Osc3Glide": "OSC Glide 3",
    "Osc3Level": "OSC Level 3",
    "Osc3Note": "OSC Note 3",
    "Osc3Octave": "OSC Octave 3",
    "Osc3Pan": "OSC Pan 3",
    "Osc3Shape": "OSC Shape 3",
    "Osc4Freq": "OSC Frequency 4",
    "Osc4Level": "OSC Level 4",
    "Osc4Pan": "OSC Pan 4",
    "Osc4Shape": "OSC Shape 4",
    "Oscillator": "Oscillator",
    "Output": "Output",
    "Overdub": "Overdub",
    "Pan": "Pan",
    "Pan Speed": "Pan Speed",
    "PanDry": "Pan Dry",
    "PanRootVoice": "Pan Root Voice",
    "PanVoice1": "Pan Voice 1",
    "PanVoice2": "Pan Voice 2",
    "PanVoice3": "Pan Voice 3",
    "Pattern": "Pattern",
    "Peak": "Peak",
    "PeakReduction": "Peak Reduction",
    "Pedal": "Pedal Position",
    "Phasing": "Phasing",
    "Pitch": "Pitch",
    "Pitch2": "Pitch 2",
    "PitchMix": "Pitch Mix",
    "PitchVoice1": "Pitch Voice 1",
    "PitchVoice2": "Pitch Voice 2",
    "PitchVoice3": "Pitch Voice 3",
    "Playback": "Playback",
    "Predelay": "Pre-Delay",
    "Presence": "Presence",
    "Preset": "Preset",
    "PullDiode": "Pull Diode",
    "PushDiode": "Push Diode",
    "Q": "Q",
    "R Polarity": "R Polarity",
    "Ramp": "Ramp",
    "RampTime": "Ramp Time",
    "Range": "Range",
    "Rate": "Rate",
    "Ratio": "Ratio",
    "RealTimeSwitch": "Real Time Switch",
    "Recycle": "Recycle",
    "Regen": "Regen",
    "Rel Offset": "Release Offset",
    "Release": "Release",
    "Res": "Res",
    "Resonance": "Resonance",
    "Return": "Return",
    "Right": "Right",
    "Right Time": "Right Time",
    "RightBoost": "Right Boost",
    "RightFeedback": "Right Feedback",
    "RiseTime": "Rise Time",
    "RiseTimeSwitch": "Rise Time Switch",
    "RFeedback": "Right Feedback",
    "Ripple": "Ripple",
    "RTime": "Right Time",
    "SSwitch": "SSwitch",
    "Sag": "Sag",
    "SampleRate": "Samplerate",
    "Saturation": "Saturation",
    "Scale": "Scale",
    "ScaleVoice1": "Scale Voice 1",
    "ScaleVoice2": "Scale Voice 2",
    "Send": "Send",
    "Sens": "Sensitivity",
    "Sensitivity": "Sensitivity",
    "Shape": "Shape",
    "ShapeVoice1": "Shape Voice 1",
    "ShapeVoice2": "Shape Voice 2",
    "ShapeVoice3": "Shape Voice 3",
    "Shift": "Shift",
    "Slop": "Slop",
    "SlowSpeed": "Slow Speed",
    "Source": "Source",
    "Space": "Space",
    "Speed": "Speed",
    "Splice": "Splice",
    "Spread": "Spread",
    "Stability": "Stability",
    "Stage": "Stage",
    "Stages": "Stages",
    "Start": "Start",
    "Step1": "Step 1",
    "Step2": "Step 2",
    "Step3": "Step 3",
    "Step4": "Step 4",
    "Steps": "Steps",
    "Sub": "Sub",
    "Sustain": "Sustain",
    "SW1": "SW1",
    "SW2": "SW2",
    "SW3": "SW3",
    "SW4": "SW4",
    "SweepDepth": "Sweep Depth",
    "SweepResonance": "Sweep Resonance",
    "SweepShape": "Sweep Shape",
    "SweepSpeed": "Sweep Speed",
    "SweepSpread": "Sweep Spread",
    "SweepStart": "Sweep Start",
    "SweepSymmetry": "Sweep Symmetry",
    "Swell": "Swell",
    "SyncSelect1": "Sync Select 1",
    "SyncSelect2": "Sync Select 2",
    "SynthPreset": "Synth Preset",
    "Tap1Delay": "Tap Delay 1",
    "Tap1Level": "Tap Level 1",
    "Tap1Pan": "Tap Pan 1",
    "Tap2Delay": "Tap Delay 2",
    "Tap2Level": "Tap Level 2",
    "Tap2Pan": "Tap Pan 2",
    "Tap3Delay": "Tap Delay 3",
    "Tap3Level": "Tap Level 3",
    "Tap3Pan": "Tap Pan 3",
    "Tap4Delay": "Tap Delay 4",
    "Tap4Level": "Tap Level 4",
    "Tap4Pan": "Tap Pan 4",
    "Tap5Delay": "Tap Delay 5",
    "Tap5Level": "Tap Level 5",
    "Tap5Pan": "Tap Pan 5",
    "Tap6Delay": "Tap Delay 6",
    "Tap6Level": "Tap Level 6",
    "Tap6Pan": "Tap Pan 6",
    "Taper": "Taper",
    "TempoSync1": "Tempo Sync 1",
    "TempoSync2": "Tempo Sync 2",
    "Thick": "Thick",
    "Thresh": "Threshold",
    "Threshold": "Threshold",
    "Time": "Time",
    "Time1": "Time 1",
    "Time2": "Time 2",
    "Toe": "Toe",
    "Tone": "Tone",
    "TrebFreq": "Treble Frequency",
    "Treble": "Treble",
    "Type": "Type",
    "Version": "Version",
    "VibratoDepth": "Vibrato Depth",
    "VibratoRate": "Vibrato Rate",
    "Voice": "Voice",
    "Vol Sens": "Volume Sensitivity",
    "Volsens": "Volume Sensitivity",
    "VolSens": "Volume Sensitivity",
    "VolumeTaper": "Volume Taper Curve",
    "Wave": "Wave",
    "WaveShape": "Wave Shape",
    "Wet Level": "Wet Level",
    "Width": "Width",
    "Wow Flt": "Wow Flt",
    "WowFlutter": "Wow Flutter",
    "Xover": "Crossover"
};

export { hxLabels };